//! In-app SSH launcher for cold-starting a headless Lich session.
//!
//! # Why this exists
//!
//! VellumFE can already *attach* to a headless Lich (`--without-frontend
//! --detachable-client=PORT`) — attach/detach as often as you like. The gap:
//! every Lich-based mode needs Lich to be *already running*. Shattered
//! characters can be launched headless conveniently, but a Prime character
//! strands you at RDP just to run one launch command.
//!
//! This module closes that gap without an always-on daemon. Over an existing
//! WireGuard/Tailscale tunnel, VellumFE SSHes into the home PC, runs the
//! `rubyw lich.rbw ... --detachable-client=PORT` command (spawned *detached*
//! so it survives the SSH channel closing), waits for the port to open, and
//! hands the resulting `host:port` to the unchanged attach path in
//! [`crate::network::LichConnection`]. SSHD is the pre-existing listener;
//! nothing new is exposed to the internet.
//!
//! # Security model
//!
//! - Auth is a **dedicated** ed25519 keypair generated by VellumFE. The
//!   private half lives only in the OS secure store (keyring on desktop,
//!   Keychain/Keystore on mobile), never on a command line or in a config
//!   file. The user pastes the public half into the home PC's
//!   `authorized_keys` once.
//! - Host keys are pinned on first use (TOFU) to a launcher-owned
//!   known-hosts file; a changed key hard-fails with a MITM warning.
//! - Because the key is purpose-built, users can restrict it server-side
//!   (`restrict,command="..."`) so a leaked key can only launch the game,
//!   not open a shell.

pub mod config;
pub mod flow;
pub mod session_lifecycle;
pub mod ssh;
